### ISSUE TITLE
part counts are off when buying multiple bundles with different user-selected variants

### ISSUE THREAD

**Issue by yf6** [spree-contrib/spree-product-assembly#120]
Consider the following set up:

Product A has 2 variants: X and Y
Product B has 2 variants: M and N
Product C has 2 parts: product A and product B, with both variants user selectable.

Now go to the shop and add the following to cart: 
product C with variants X, M
product C with variants Y, N

In cart, you expect to see 2 product C with ONE of each variants: X, Y, M, N
But in fact, it shows 2 product C with TWO of each variants: X, Y, M, N, and it looks the same on admin side too. 

I originally thought that might be an UI issue, but the more I look into it, the more it seems like a deeper logic issue?

**Comment by vinniefranco** [comment]
@yf6 Passed this info to one of our devs. We should be getting to it soon

**Comment by yf6** [comment]
:+1: Thanks.

**Comment by vinniefranco** [comment]
@yf6 the other dev has been busy so I dived in just now. After thinking about this a bit I realized that the example is a special case. It is only expected behavior if you are adding another bundle with variants that do not already exist in the existing order bundle, if that's not the case, it gets weird.

### Example:

##### Setup:
Product A - 2 variants Blue, Red
Product B - 2 variants Large, Medium

Product C parts: A & B.

#### Exercise:

1. Navigate to product page
2. Add Product C with Red, Large
3. Navigate back to product page
4. Add Product C with Red, Medium
5. Navigate back to product page
6. Add Product C with Red, Large
7. View cart.

#### Outcome (If suggested modifications are made):

Cart has:
Product C x 3 with (3 Red, 2 Large, 1 Medium)

Decrementing quantity presents a problem too... what was it supposed to remove? Shouldn't the outcome be that each bundled product actually generates a new line item, not increment an existing quantity, and merge parts? 

Not sure if Spree will allow completely separate line items with the same SKU. Requires further investigation....

**Comment by yf6** [comment]
You example is right. And yes, the UI is going to look hairy. I see two possibly solutions:
1) what you said, to have each bundle be a different line item and only group the ones with identical variants combo - spree does similar stuff if you have multiple variants of the same product in cart
2) less ideal, but maybe works better with spree, have the parts be separate line items - but then you don't have much of a notion of a bundle in cart anymore - and you would expect to be able to remove each parts separately from the cart - which may or may not be desired depending on the use case.

**Comment by vinniefranco** [comment]
@yf6 Fixed!

**Comment by yf6** [comment]
:+1:
